### ISSUE TITLE
Threading is not implemented for SLIM

### ISSUE THREAD

**Issue by ekluzek** [marysa/SimpleLand#15]
From issue #14 I'm thinking there are problems with threading that don't allow SLIM to work with threads. I also see this in that the working cases I have from @marysa and Wenwen are all without threading. CAM normally runs with threading and has better performance with threads so this is a configuration that we should get working.+

**Comment by ekluzek** [comment]
pelayouts that @marysa and Wenwen are using:

> Comp  NTASKS  NTHRDS  ROOTPE
> CPL :    360/     1;      0
> ATM :    360/     1;      0
> LND :    360/     1;      0
> ICE :    360/     1;      0
> OCN :    360/     1;      0
> ROF :    360/     1;      0
> GLC :    360/     1;      0
> WAV :    360/     1;      0
> ESP :      1/     1;      0
> 
> Comp  NTASKS  NTHRDS  ROOTPE
> CPL :    288/     1;     36
> ATM :    288/     1;      0
> LND :    144/     1;     36
> ICE :    108/     1;     36
> OCN :    288/     1;     36
> ROF :     40/     1;     36
> GLC :     36/     1;     36
> WAV :     36/     1;     36
> ESP :      1/     1;      0

Note, the last one is malformed since the rootpe for surface components only allows one node for CAM, while CAM is running with 8 nodes.

**Comment by marysa** [comment]
I have a faint memory of talking to Gordon and Ahmed about something to do with threading waaaaay back when I was just starting to put SLIM into Fortran (had it loosely written up in MatLab before that). The take-away I remember was that I didn't have to worry about how I coded something specific to Fortran (vs MatLab) if I only ever ran with one thread, and they thought this would be fine, so that is what I did! Not super helpful, since I can't remember what it was that I would have had to do differently to make it work with threading, but it was only ever supposed to work on a single thread!

**Comment by ekluzek** [comment]
Ahhh, thanks for that insight. Yes, this means we'll need to do a bunch of work to get threading to work. We'll want to go through everything with threading and make sure it's correct before using it. Threading is weird in that it's often both easier to get working because everything is in shared memory, but also can be harder to find problems. So I see why they suggested you ditch working on threading.

But for now I'll just disable the option to try it with threads in SLIM. I can do that both in the Fortran code and in the scripting. There's no real reason we need threading to work now, we could add it in much later as something to add just if we think it'll help performance running with cam.

**Comment by slevisconsulting** [comment]
The bounds_clump bug resolved in #42 may explain SLIM's earlier problems with threading. For now though I am not reopening this issue.

**Comment by ekluzek** [comment]
There's likely multiple issues with threading since it was built without it and has never worked with it. You are right #42 did resolve a really major one (although our solution also means that threading wouldn't help).  So I agree let's leave it as a limitation, until at some point in time when someone has a need for it.
